/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database reachability */
        get: operations["HealthController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange email and password for a token pair */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token; the old one is revoked */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the presented refresh token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every session for the signed-in user */
        post: operations["AuthController_logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update name or avatar */
        patch: operations["AuthController_updateMe"];
        trace?: never;
    };
    "/walkers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search walkers, newest-rated first */
        get: operations["WalkersController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/walkers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One walker */
        get: operations["WalkersController_byId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/dogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's dogs */
        get: operations["MeController_dogs"];
        put?: never;
        /** Add a dog */
        post: operations["MeController_addDog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/dogs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a dog */
        delete: operations["MeController_removeDog"];
        options?: never;
        head?: never;
        /** Update a dog */
        patch: operations["MeController_editDog"];
        trace?: never;
    };
    "/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's addresses, door codes decrypted */
        get: operations["MeController_addresses"];
        put?: never;
        /** Add an address */
        post: operations["MeController_addAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/walker-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The walker profile, or null */
        get: operations["MeController_walkerProfile"];
        /** Create or replace the walker profile */
        put: operations["MeController_putWalkerProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/walker-profile/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Go available or unavailable */
        patch: operations["MeController_setAvailability"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /**
             * @description `degraded` whenever the database is unreachable.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @description Process uptime in whole seconds.
             * @example 421
             */
            uptimeSec: number;
            /**
             * @description Result of `SELECT 1` under a 2 second timeout.
             * @enum {string}
             */
            db: "up" | "down";
            /**
             * @description Server package version.
             * @example 0.1.0
             */
            version: string;
        };
        MeDto: {
            id: string;
            /** @example levan@modimodi.ge */
            email: string;
            /** @example ლევან ხ. */
            name: string;
            avatarKey?: string | null;
            isOwner: boolean;
            isWalker: boolean;
            /** @description True once a walker profile exists. */
            hasWalkerProfile: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PublicWalkerDto: {
            id: string;
            /** @example ნინო ბ. */
            name: string;
            /** @description CDN URL, resolved from the stored object key. */
            avatarUrl?: string | null;
            /**
             * @description Denormalised average, 0–5.
             * @example 4.9
             */
            rating: number;
            /** @example 127 */
            reviewCount: number;
            /**
             * @description Price for 30 minutes, in tetri.
             * @example 1500
             */
            price30Tetri: number;
            /** @description True once an admin has verified identity. */
            verified: boolean;
            isAvailableNow: boolean;
            /**
             * @example [
             *       "ვაკე"
             *     ]
             */
            districts: string[];
            /** @example სამი წელია ვასეირნებ ძაღლებს ვაკეში. */
            bio: string;
            /** @description Always null until location lands. The field exists so the client contract does not change when it starts being populated. */
            distanceKm?: number | null;
        };
        WalkerPageDto: {
            items: components["schemas"]["PublicWalkerDto"][];
            /** @description Pass back as ?cursor= for the next page. Null at the end. */
            nextCursor?: string | null;
        };
        DogDto: {
            id: string;
            /** @example ბობი */
            name: string;
            /** @example ლაბრადორი */
            breed: string;
            /**
             * @description Date only. The app renders "3 წლის" from this.
             * @example 2023-03-14
             */
            birthDate: string;
            photoUrl?: string | null;
            notes?: string | null;
            sizeKg?: number | null;
        };
        OkDto: {
            /** @example true */
            ok: boolean;
        };
        AddressDto: {
            id: string;
            /** @example სახლი */
            label: string;
            /** @example ვაკე */
            district: string;
            /** @example აბაშიძის 12 */
            street: string;
            /** @description Decrypted, and only ever returned to the address owner. */
            entranceCode?: string | null;
        };
        WalkerProfileDto: {
            bio: string;
            /**
             * @description Per 30 minutes, in tetri.
             * @example 1500
             */
            price30Tetri: number;
            districts: string[];
            isAvailableNow: boolean;
            verified: boolean;
            /** @example 4.9 */
            rating: number;
            /** @example 127 */
            reviewCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The database answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
            /** @description The database did not answer within 2 seconds. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    WalkersController_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkerPageDto"];
                };
            };
        };
    };
    WalkersController_byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicWalkerDto"];
                };
            };
        };
    };
    MeController_dogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogDto"][];
                };
            };
        };
    };
    MeController_addDog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogDto"];
                };
            };
        };
    };
    MeController_removeDog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkDto"];
                };
            };
        };
    };
    MeController_editDog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DogDto"];
                };
            };
        };
    };
    MeController_addresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressDto"][];
                };
            };
        };
    };
    MeController_addAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressDto"];
                };
            };
        };
    };
    MeController_walkerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkerProfileDto"];
                };
            };
        };
    };
    MeController_putWalkerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkerProfileDto"];
                };
            };
        };
    };
    MeController_setAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkerProfileDto"];
                };
            };
        };
    };
}
